[versions]
java = "17"
minecraft = "1.20.1"
fabric-loader = "0.15.11"
fabric-loom = "1.7-SNAPSHOT"
fabric-api = "0.92.2+1.20.1"
mixinsquared = "0.2.0-beta.5"

buildingwands = "2.6.9_release_fabric_1.20.1"
cctweaked = "MlxrTZqO"
enchantedverticalslabs = "1.9.1"
forgeconfigapiport = "v8.0.0-1.20.1-Fabric"
fwaystones = "3.3.2+mc1.20.1"
gliders = "1.1.5+fabric"
portinglib = "2.3.4+1.20.1"

itemcollectors = "1.1.10-fabric-mc1.20"
supermartijn642core = "1.1.17-fabric-mc1.20.1"

appbot = "1.5.0-fabric"
botania = "1.20.1-445-fabric"
emi = "1.1.10+1.20.1+fabric"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

buildingwands = { module = "maven.modrinth:building-wands", version.ref = "buildingwands" }
cctweaked = { module = "maven.modrinth:cc-tweaked", version.ref = "cctweaked" }
enchantedverticalslabs = { module = "maven.modrinth:enchanted-vertical-slabs", version.ref = "enchantedverticalslabs"}
forgeconfigapiport = { module = "maven.modrinth:forge-config-api-port", version.ref = "forgeconfigapiport" }
fwaystones = { module = "maven.modrinth:fwaystones", version.ref = "fwaystones" }
gliders = { module = "maven.modrinth:gliders", version.ref = "gliders" }
portinglib-config = { module = "io.github.fabricators_of_create.Porting-Lib:config", version.ref = "portinglib" }
portinglib-model-loader = { module = "io.github.fabricators_of_create.Porting-Lib:model_loader", version.ref = "portinglib" }

itemcollectors = { module = "maven.modrinth:item-collectors", version.ref = "itemcollectors" }
supermartijn642core = { module = "maven.modrinth:supermartijn642s-core-lib", version.ref = "supermartijn642core" }

appbot = { module = "maven.modrinth:applied-botanics", version.ref = "appbot" }
botania = { module = "maven.modrinth:botania", version.ref = "botania" }
emi = { module = "maven.modrinth:emi", version.ref = "emi" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
